"""empty message

Revision ID: 17da16814e2
Revises: 40fdaa12db1
Create Date: 2016-12-05 21:21:37.367673

"""

# revision identifiers, used by Alembic.
revision = '17da16814e2'
down_revision = '40fdaa12db1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
