"""empty message

Revision ID: 27bf62694ee
Revises: 322041300c8
Create Date: 2016-12-06 19:37:30.521778

"""

# revision identifiers, used by Alembic.
revision = '27bf62694ee'
down_revision = '322041300c8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest_typing', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('quest_typing', sa.Column('operator_id', sa.Integer(), nullable=True))
    op.add_column('quest_typing', sa.Column('quest_id', sa.Integer(), nullable=True))
    op.add_column('quest_typing', sa.Column('state', sa.Integer(), nullable=True))
    op.drop_column('quest_typing', 'oper_id')
    op.drop_column('quest_typing', 'oper_state')
    op.drop_column('quest_typing', 'oper_memo')
    op.drop_column('quest_typing', 'oper_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest_typing', sa.Column('oper_date', mysql.DATETIME(), nullable=False))
    op.add_column('quest_typing', sa.Column('oper_memo', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('quest_typing', sa.Column('oper_state', mysql.INTEGER(display_width=11), nullable=True))
    op.add_column('quest_typing', sa.Column('oper_id', mysql.INTEGER(display_width=11), nullable=True))
    op.drop_column('quest_typing', 'state')
    op.drop_column('quest_typing', 'quest_id')
    op.drop_column('quest_typing', 'operator_id')
    op.drop_column('quest_typing', 'date')
    ### end Alembic commands ###
