"""empty message

Revision ID: 2881437bc
Revises: 2af8e8acd09
Create Date: 2017-04-17 22:04:56.992233

"""

# revision identifiers, used by Alembic.
revision = '2881437bc'
down_revision = '2af8e8acd09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
