"""empty message

Revision ID: 31b9735458e
Revises: 58e0487bda4
Create Date: 2016-12-30 21:22:39.533342

"""

# revision identifiers, used by Alembic.
revision = '31b9735458e'
down_revision = '58e0487bda4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_quest', sa.Column('group', sa.Integer(), nullable=True))
    op.add_column('sub_quest', sa.Column('operator_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_quest', 'operator_id')
    op.drop_column('sub_quest', 'group')
    ### end Alembic commands ###
