"""empty message

Revision ID: 322041300c8
Revises: 17da16814e2
Create Date: 2016-12-05 23:16:03.840788

"""

# revision identifiers, used by Alembic.
revision = '322041300c8'
down_revision = '17da16814e2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_review_log')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_review_log',
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('exam_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('reviewer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('review_state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('review_memo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('review_date', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
