"""empty message

Revision ID: 3ab8946f3af
Revises: 557855d32e6
Create Date: 2017-01-22 19:49:36.800348

"""

# revision identifiers, used by Alembic.
revision = '3ab8946f3af'
down_revision = '557855d32e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('struct', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'struct')
    ### end Alembic commands ###
