"""empty message

Revision ID: 3bc79113378
Revises: 2881437bc
Create Date: 2017-05-23 19:33:43.849997

"""

# revision identifiers, used by Alembic.
revision = '3bc79113378'
down_revision = '2881437bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
