"""empty message

Revision ID: 40fdaa12db1
Revises: 2919c7d710c
Create Date: 2016-12-05 21:08:39.032006

"""

# revision identifiers, used by Alembic.
revision = '40fdaa12db1'
down_revision = '2919c7d710c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest', sa.Column('insert_user_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quest', 'insert_user_id')
    ### end Alembic commands ###
