"""empty message

Revision ID: 42994ded567
Revises: af63f5814e
Create Date: 2016-12-05 19:48:33.382786

"""

# revision identifiers, used by Alembic.
revision = '42994ded567'
down_revision = 'af63f5814e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
