"""empty message

Revision ID: 439a468cac9
Revises: 2fa1aadf80
Create Date: 2016-12-31 18:11:06.822545

"""

# revision identifiers, used by Alembic.
revision = '439a468cac9'
down_revision = '2fa1aadf80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_quest', sa.Column('finish_state', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_quest', 'finish_state')
    ### end Alembic commands ###
