"""empty message

Revision ID: 4ab6d39eefb
Revises: 3bc79113378
Create Date: 2017-05-23 19:35:59.755325

"""

# revision identifiers, used by Alembic.
revision = '4ab6d39eefb'
down_revision = '3bc79113378'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('is_super', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'is_super')
    ### end Alembic commands ###
