"""empty message

Revision ID: 557855d32e6
Revises: 220f38e1545
Create Date: 2017-01-09 21:12:58.404616

"""

# revision identifiers, used by Alembic.
revision = '557855d32e6'
down_revision = '220f38e1545'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('exam_date', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'exam_date')
    ### end Alembic commands ###
