"""empty message

Revision ID: 58e0487bda4
Revises: 44bf7dfc2af
Create Date: 2016-12-29 21:00:49.393300

"""

# revision identifiers, used by Alembic.
revision = '58e0487bda4'
down_revision = '44bf7dfc2af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest', sa.Column('correct_answer2', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quest', 'correct_answer2')
    ### end Alembic commands ###
