"""empty message

Revision ID: 92af9d8e96
Revises: 31a5c3af7a3
Create Date: 2017-03-07 19:41:27.188576

"""

# revision identifiers, used by Alembic.
revision = '92af9d8e96'
down_revision = '31a5c3af7a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('order', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'order')
    ### end Alembic commands ###
