"""empty message

Revision ID: af63f5814e
Revises: 4b6fef4b448
Create Date: 2016-12-05 19:22:27.212304

"""

# revision identifiers, used by Alembic.
revision = 'af63f5814e'
down_revision = '4b6fef4b448'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_log',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('quest_no', sa.Integer(), nullable=True),
    sa.Column('refer_user_id', sa.Integer(), nullable=True),
    sa.Column('log_state', sa.Integer(), nullable=True),
    sa.Column('log_type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_typing',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('quest_no', sa.Integer(), nullable=True),
    sa.Column('oper_id', sa.Integer(), nullable=True),
    sa.Column('oper_state', sa.Integer(), nullable=True),
    sa.Column('oper_memo', sa.String(length=100), nullable=True),
    sa.Column('oper_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('region', 'code',
               existing_type=mysql.CHAR(length=6),
               nullable=True)
    op.alter_column('region', 'name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('region', 'pid',
               existing_type=mysql.SMALLINT(display_width=5),
               nullable=True,
               existing_server_default='0')
    op.alter_column('school', 'ctid',
               existing_type=mysql.SMALLINT(display_width=5),
               nullable=True,
               existing_server_default='0')
    op.alter_column('school', 'name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.drop_index('pid', 'school')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('pid', 'school', ['ctid'], unique=False)
    op.alter_column('school', 'name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('school', 'ctid',
               existing_type=mysql.SMALLINT(display_width=5),
               nullable=False,
               existing_server_default='0')
    op.alter_column('region', 'pid',
               existing_type=mysql.SMALLINT(display_width=5),
               nullable=False,
               existing_server_default='0')
    op.alter_column('region', 'name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('region', 'code',
               existing_type=mysql.CHAR(length=6),
               nullable=False)
    op.drop_table('quest_typing')
    op.drop_table('quest_log')
    ### end Alembic commands ###
