class Permission():
    UPLOAD_PERMISSION = ['PaperUpload', 'PaperUploadList']
    CONFIRM_PERMISSION = ['WaitConfirm', 'PaperConfirm', 'ConfirmList']
    DEAL_PERMISSION = ['WaitDeal', 'PaperDeal', 'DealList']
    INPUT_PERMISSION = ['WaitInput', 'PaperInput', 'InputList']
    ANSWER_PERMISSION = ['WaitAnswer', 'PaperAnswer', 'AnswerList']
    CHECK_PERMISSION = ['WaitCheck', 'QuestCheck', 'CheckList']
    JUDGE_PERMISSION = ['WaitJudge', 'QuestJudge', 'JudgeList']
    VERIFY_PERMISSION = ['WaitVerify', 'QuestVerify', 'VerifyList']
    FAST_PERMISSION = ['PaperIsFast']